### ISSUE TITLE
Missing files for Release_Small_title.tsv and title_entity_emb.pkl

### ISSUE THREAD

**Issue by thangld201** [taoqi98/HieRec#3]
Thanks for sharing the code, can I ask which files in the MIND dataset are equivalent for Release_Small_title.tsv and title_entity_emb.pkl, or how should I process further to get these files? (preprocessing.py)
```
    with open(os.path.join(KG_root_path,'title_entity_emb.pkl'),'rb') as f:
        title_entity_emb = pickle.load(f)
```
```
def load_news_entity(news_index,KG_root_path):
    with open(os.path.join(KG_root_path,'Release_Small_title.tsv')) as f:
        lines = f.readlines()
```

**Comment by taoqi98** [comment]
Thank you for your attention on our work. Due to license issue of MIND dataset, I am not sure whether I can publicly share processed KG data on MIND. Thus, I want to privately share KG data with you. You can send an email to me (taoqi.qt@gmail.com) and I will reply the KG data ASAP.
